@noteId = 00000000-0000-0000-0000-000000000000

### Add Note
POST {{baseUrl}}/notes
Content-Type: application/json

{
    "content": "Test Note"
}

> {%
client.global.set("noteId", response.body.id);
client.log("Saved {{noteId}} as: " + response.body.id);
%}

### Update Note
PUT {{baseUrl}}/notes/{{noteId}}
Content-Type: application/json

{
    "content": "Updated Test Note"
}

### Delete Note
DELETE {{baseUrl}}/notes/{{noteId}}

### Get Note by Id
GET {{baseUrl}}/notes/{{noteId}}

### List Notes
GET {{baseUrl}}/notes/1/10