@noteId = 00000000-0000-0000-0000-000000000000

### Get Hello, World!
GET {{baseUrl}}/notes/hello

### Add Note
POST {{baseUrl}}/notes
Content-Type: application/json

{
    "content": "Test Note"
}

> {%
client.global.set("noteId", response.body.id);
client.log("Saved {{noteId}} as: " + response.body.id);
%}

### Get Note by Id
GET {{baseUrl}}/notes/{{noteId}}